### ISSUE TITLE
Generate error for ESS ImperatrizPS file in DBAR section

### ISSUE THREAD

**Issue by iagochavarry** [LAMPSPUC/PWF.jl#28]
In ESS ImperatrizPS file, last DBAR buses are not obeying DBAR convention, but the code didn't throw an error

**Comment by PHamacher** [comment]
The inconsistency on the file was that, in some buses, the column 'operation' was filled with the character 'M', whereas the package was expecting an Int64. Therefore, the necessary change involves editing the code in order to accept Char inputs on column 'operation'
